version: "3"

services:
  sentry2telegram:
    image: denoland/deno:1.42.4
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - BASE_URL=${BASE_URL}
    restart: unless-stopped
    volumes:
      - ./src:/app
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: run --watch --allow-all /app/main.ts
